### ISSUE TITLE
Some market data stopped working

### ISSUE THREAD

**Issue by ApostolosB** [andywuest/harbour-watchlist#72]
Ie Gold or USD/EUR are not working any more. If you add them they don't display a price.

**Comment by andywuest** [comment]
confirmed.

**Comment by andywuest** [comment]
fixed with 0fed3218df28900df2fa6d4cb556efed51122750 - unfortunately the commit comment is not correct.

**Comment by andywuest** [comment]
fixed with 0.8.3 - please try. since the ids of the market data elements have changed, you have to remove the old ones and add them again - so they use the new internal id.

**Comment by ApostolosB** [comment]
Gold and Silver (and possibly others) still don't work with the latest version from the Jolla Store

**Comment by andywuest** [comment]
You are right - gold and silver (and i guess all the other commodiities) haven't been updated since dezember. i will check this. I really only did update the currencies...
Thanks.

**Comment by ApostolosB** [comment]
Also the currency symbol for EUR/USD doesn't work. I didn't test other currencies.

**Comment by andywuest** [comment]
plase try again. gold and silver should work now. you have to remove the old entries and add them again.

**Comment by ApostolosB** [comment]
Yeah it works. Thanks.

**Comment by spodermenpls** [comment]
@andywuest Unfortunately, the precious metals Gold, Silver, Platinum and Palladium no longer get updates in the market data section on my end (last date for Platinum was January, for Gold and Silver in June). I tried removing and re-adding the entries, but now there are only two hyphens shown as placeholders for date and price. Is this just an issue on my end, or did some API change once again upstream?

**Comment by andywuest** [comment]
Upstream changed - i will have a look at the problems - crypto currencies are also no longer properly updated

**Comment by spodermenpls** [comment]
> Upstream changed - i will have a look at the problems - crypto currencies are also no longer properly updated

Thank you for the quick fix!
